# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a07b060dec70406eb145384ee8fc2639978a7da11c856f7d3630fd4d1507de2e0a9337325a4bf2d922c070547f881464ccfbd7401ada8c6fd284388a3c5dd7

test:
  secret_key_base: 71102e8e219ea1d7b555a7bb71bf9e040b9493c4b7e2803d6af3298d6c35cf3eb1d76926d912471b2ac9203772766ed583dd77482c36fcd7e2e64e32d9a02ac8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
